// <auto-generated />
using System;
using CodeFirst.A_DAL.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeFirst.Migrations
{
    [DbContext(typeof(ParkingManageContext))]
    partial class ParkingManageContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CodeFirst.A_DAL.Models.Parking", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Area")
                        .HasColumnType("float")
                        .HasColumnName("Diện tích");

                    b.Property<int>("Capacity")
                        .HasColumnType("int")
                        .HasColumnName("Sức chứa");

                    b.Property<DateTime>("Establish")
                        .HasColumnType("datetime2");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Vị trí");

                    b.Property<string>("Owner")
                        .IsRequired()
                        .HasColumnType("nvarchar(100)")
                        .HasColumnName("Chủ sở hữu");

                    b.HasKey("Name");

                    b.ToTable("Parkings");
                });

            modelBuilder.Entity("CodeFirst.A_DAL.Models.Vehicle", b =>
                {
                    b.Property<string>("VCP")
                        .HasColumnType("varchar(10)")
                        .HasColumnName("Biển số xe");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Tên xe");

                    b.Property<string>("OwnerIdCard")
                        .IsRequired()
                        .HasColumnType("varchar(12)")
                        .HasColumnName("Căn cước công dân");

                    b.Property<string>("ParkingMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Hình thức gửi xe");

                    b.Property<string>("ParkingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("Loại xe");

                    b.HasKey("VCP");

                    b.HasIndex("ParkingName");

                    b.ToTable("vehicles");
                });

            modelBuilder.Entity("CodeFirst.A_DAL.Models.Vehicle", b =>
                {
                    b.HasOne("CodeFirst.A_DAL.Models.Parking", null)
                        .WithMany("Vehicles")
                        .HasForeignKey("ParkingName")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CodeFirst.A_DAL.Models.Parking", b =>
                {
                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
